# -*- coding: utf-8 -*-
"""Lab_NAS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DOcZ5eF0bHNe933WsHY9xD9zPyBucdE_
"""

from google.colab import drive
drive.flush_and_unmount()

from google.colab import drive
drive.mount('/content/drive')

# =========================
# Librerie
# =========================
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# =========================
# Percorso del file CSV
# =========================
path = "/content/drive/MyDrive/ColabData/NAS_dataset_B.csv"

# =========================
# Caricamento dataset
# header=None mantiene tutte
# le 75 righe originali
# =========================
B = pd.read_csv(
    path,
    header=None
).to_numpy()

# =========================
# Controllo dimensioni
# =========================
print("Dimensioni dataset:", B.shape)

# Prime righe
print(B[:5])

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.svm import SVR
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error

# =========================
# Parametri
# =========================
m, n = B.shape

n_trial = 10
n_test = 10
n_val = 5

n_dati = m - n_test

data_cons = 23      # numero feature input
label = 32          # colonna target



# Dati train+validation
A_original = B[:n_dati, :]

# Array errori
err_SVR = np.zeros(n_trial)
err_RF = np.zeros(n_trial)
err_HYBRID = np.zeros(n_trial)

# Random seed
rng = np.random.default_rng(seed=42)

# =========================
# Training + validation
# =========================
for j in range(n_trial):

    # Shuffle dati
    ii = rng.permutation(n_dati)
    A = A_original[ii, :]

    # =========================
    # TRAIN
    # =========================
    X_train = A[:n_dati - n_val, :data_cons]
    y_train = A[:n_dati - n_val, label_idx]

    # =========================
    # VALIDATION
    # =========================
    X_val = A[n_dati - n_val:n_dati, :data_cons]
    y_val = A[n_dati - n_val:n_dati, label_idx]

    # =========================
    # SVR
    # =========================
    mdl_svr = make_pipeline(
        StandardScaler(),
        SVR(
            kernel="rbf",
            gamma="scale"
        )
    )

    mdl_svr.fit(X_train, y_train)

    yfit_SVR = mdl_svr.predict(X_val)

    err_SVR[j] = mean_absolute_error(
        y_val,
        yfit_SVR
    )

    # =========================
    # RANDOM FOREST
    # =========================
    mdl_rf = RandomForestRegressor(
        n_estimators=100,
        max_depth=None,
        min_samples_split=2,
        min_samples_leaf=1,
        bootstrap=True,
        random_state=42
    )

    mdl_rf.fit(X_train, y_train)

    yfit_RF = mdl_rf.predict(X_val)

    err_RF[j] = mean_absolute_error(
        y_val,
        yfit_RF
    )

    # =========================
    # MODELLO HYBRID
    # =========================
    yfit_HYBRID = (yfit_SVR + yfit_RF) / 2

    err_HYBRID[j] = mean_absolute_error(
        y_val,
        yfit_HYBRID
    )

# =========================
# Errori medi
# =========================
err_mean_SVR = np.mean(err_SVR)
err_mean_RF = np.mean(err_RF)
err_mean_HB = np.mean(err_HYBRID)

print("\n===== VALIDATION ERRORS =====")
print("SVR     :", err_mean_SVR)
print("RF      :", err_mean_RF)
print("HYBRID  :", err_mean_HB)

# =========================
# TEST FINALE
# =========================
X_test = B[n_dati:m, :data_cons]
y_test = B[n_dati:m, label_idx]

# Predizioni
yfit_SVR_test = mdl_svr.predict(X_test)
yfit_RF_test = mdl_rf.predict(X_test)

# Hybrid
yfit_test = (yfit_SVR_test + yfit_RF_test) / 2

# =========================
# Tabella risultati
# =========================
PRED = np.column_stack([
    y_test,
    yfit_SVR_test,
    yfit_RF_test,
    yfit_test
])

PRED_df = pd.DataFrame(
    PRED,
    columns=[
        "Valore_reale",
        "Pred_SVR",
        "Pred_RF",
        "Pred_Hybrid"
    ]
)

print("\n===== TEST PREDICTIONS =====")
print(PRED_df)

# =========================
# GRID SEARCH SVR
# Ricerca automatica migliori:
# - kernel
# - C
# - gamma
# - epsilon
# =========================

from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

# =========================
# Pipeline SVR
# =========================
svr_pipeline = Pipeline([
    ("scaler", StandardScaler()),
    ("svr", SVR())
])

# =========================
# Griglia iperparametri
# =========================
param_grid = [

    # =====================
    # RBF / Gaussian
    # =====================
    {
        "svr__kernel": ["rbf"],
        "svr__C": [0.1, 1, 10, 100, 1000],
        "svr__gamma": ["scale", 0.001, 0.01, 0.1, 1],
        "svr__epsilon": [0.001, 0.01, 0.1, 0.5]
    },

    # =====================
    # Polynomial
    # =====================
    {
        "svr__kernel": ["poly"],
        "svr__degree": [2, 3, 4],
        "svr__C": [0.1, 1, 10, 100],
        "svr__gamma": ["scale", 0.01, 0.1],
        "svr__epsilon": [0.01, 0.1]
    },

    # =====================
    # Sigmoid
    # =====================
    {
        "svr__kernel": ["sigmoid"],
        "svr__C": [0.1, 1, 10, 100],
        "svr__gamma": ["scale", 0.001, 0.01, 0.1],
        "svr__epsilon": [0.01, 0.1]
    },

    # =====================
    # Linear
    # =====================
    {
        "svr__kernel": ["linear"],
        "svr__C": [0.1, 1, 10, 100, 1000],
        "svr__epsilon": [0.001, 0.01, 0.1, 0.5]
    }
]

# =========================
# Grid Search
# scoring negativo perché
# sklearn minimizza
# =========================
grid_search = GridSearchCV(
    estimator=svr_pipeline,
    param_grid=param_grid,
    scoring="neg_mean_absolute_error",
    cv=5,
    n_jobs=-1,
    verbose=2
)

# =========================
# TRAINING
# =========================
grid_search.fit(X_train, y_train)

# =========================
# Migliori parametri
# =========================
print("\n===== BEST PARAMETERS =====")
print(grid_search.best_params_)

print("\n===== BEST VALIDATION MAE =====")
print(-grid_search.best_score_)

# =========================
# Miglior modello
# =========================
best_svr = grid_search.best_estimator_

# =========================
# Predizione validation
# =========================
yfit_SVR = best_svr.predict(X_val)

val_mae = mean_absolute_error(
    y_val,
    yfit_SVR
)

print("\nValidation MAE:", val_mae)

# =========================
# Predizione test
# =========================
yfit_SVR_test = best_svr.predict(X_test)

test_mae = mean_absolute_error(
    y_test,
    yfit_SVR_test
)

print("\nTest MAE:", test_mae)

# =========================
# GRID SEARCH RANDOM FOREST
# Ricerca automatica:
# - numero alberi
# - profondità
# - min samples
# - max features
# =========================

from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GridSearchCV

# =========================
# Modello base
# =========================
rf_model = RandomForestRegressor(
    random_state=42
)

# =========================
# Griglia iperparametri
# =========================
param_grid_rf = {

    # Numero alberi
    "n_estimators": [
        10,
        50,
        100,
        200,
        500
    ],

    # Profondità alberi
    "max_depth": [
        None,
        5,
        10,
        20,
        30
    ],

    # Minimo split nodo
    "min_samples_split": [
        2,
        5,
        10
    ],

    # Minimo campioni foglia
    "min_samples_leaf": [
        1,
        2,
        4
    ],

    # Numero feature per split
    "max_features": [
        "sqrt",
        "log2",
        None
    ],

    # Bootstrap
    "bootstrap": [
        True
    ]
}

# =========================
# Grid Search
# =========================
grid_search_rf = GridSearchCV(
    estimator=rf_model,
    param_grid=param_grid_rf,
    scoring="neg_mean_absolute_error",
    cv=5,
    n_jobs=-1,
    verbose=2
)

# =========================
# TRAINING
# =========================
grid_search_rf.fit(X_train, y_train)

# =========================
# Migliori parametri
# =========================
print("\n===== BEST RF PARAMETERS =====")
print(grid_search_rf.best_params_)

print("\n===== BEST RF VALIDATION MAE =====")
print(-grid_search_rf.best_score_)

# =========================
# Miglior modello RF
# =========================
best_rf = grid_search_rf.best_estimator_

# =========================
# Predizione validation
# =========================
yfit_RF = best_rf.predict(X_val)

val_mae_rf = mean_absolute_error(
    y_val,
    yfit_RF
)

print("\nRF Validation MAE:", val_mae_rf)

# =========================
# Predizione test
# =========================
yfit_RF_test = best_rf.predict(X_test)

test_mae_rf = mean_absolute_error(
    y_test,
    yfit_RF_test
)

print("\nRF Test MAE:", test_mae_rf)

# =========================
# CONFRONTO FINALE
# BEST SVR vs BEST RF
# =========================

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

# =========================
# Predizioni TEST
# =========================
y_pred_svr = best_svr.predict(X_test)
y_pred_rf = best_rf.predict(X_test)

# =========================
# Metriche SVR
# =========================
mae_svr = mean_absolute_error(y_test, y_pred_svr)
rmse_svr = np.sqrt(mean_squared_error(y_test, y_pred_svr))
r2_svr = r2_score(y_test, y_pred_svr)

# =========================
# Metriche RF
# =========================
mae_rf = mean_absolute_error(y_test, y_pred_rf)
rmse_rf = np.sqrt(mean_squared_error(y_test, y_pred_rf))
r2_rf = r2_score(y_test, y_pred_rf)

# =========================
# Tabella confronto
# =========================
comparison_df = pd.DataFrame({
    "Model": ["SVR", "Random Forest"],
    "MAE": [mae_svr, mae_rf],
    "RMSE": [rmse_svr, rmse_rf],
    "R2": [r2_svr, r2_rf]
})

print("\n===== FINAL TEST COMPARISON =====")
print(comparison_df)

# =========================
# Miglior modello
# =========================
best_model_name = comparison_df.loc[
    comparison_df["MAE"].idxmin(),
    "Model"
]

print("\nBest model on TEST set:", best_model_name)

# =========================
# Grafico confronto
# =========================
plt.figure(figsize=(10,6))

plt.plot(
    y_test,
    'o-',
    label='True Values'
)

plt.plot(
    y_pred_svr,
    's--',
    label='SVR Prediction'
)

plt.plot(
    y_pred_rf,
    'd--',
    label='RF Prediction'
)

plt.xlabel("Test Sample")
plt.ylabel("Target Value")
plt.title("SVR vs Random Forest - Test Predictions")

plt.legend()
plt.grid(True)

plt.show()

# =========================
# Tabella predizioni
# =========================
results_test = pd.DataFrame({
    "True": y_test,
    "SVR": y_pred_svr,
    "RF": y_pred_rf
})

print("\n===== TEST PREDICTIONS =====")
print(results_test)