# -*- coding: utf-8 -*-
"""Lab_VAE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a9bFOuDnQnAqEvwCHqsPoUd5XTxqFxzG

Importo le librerie necessarie:
"""

import numpy as np

import torch
import torch.nn as nn
import torch.nn.functional as F

from torch.utils.data import DataLoader, TensorDataset
from torchvision import datasets, transforms

"""Creo uno strato di sampling:"""

class Sampling(nn.Module):
    """Uses (z_mean, z_log_var) to sample z, the vector encoding a digit."""

    def forward(self, z_mean, z_log_var):
        epsilon = torch.randn_like(z_mean)
        return z_mean + torch.exp(0.5 * z_log_var) * epsilon

"""Creo l'encoder:"""

class Encoder(nn.Module):
    def __init__(self, latent_dim=2):
        super(Encoder, self).__init__()

        self.conv1 = nn.Conv2d(1, 32, kernel_size=3, stride=2, padding=1)
        self.conv2 = nn.Conv2d(32, 64, kernel_size=3, stride=2, padding=1)

        self.flatten = nn.Flatten()
        self.fc = nn.Linear(64 * 7 * 7, 16)

        self.z_mean = nn.Linear(16, latent_dim)
        self.z_log_var = nn.Linear(16, latent_dim)

        self.sampling = Sampling()

    def forward(self, x):
        x = F.relu(self.conv1(x))
        x = F.relu(self.conv2(x))

        x = self.flatten(x)
        x = F.relu(self.fc(x))

        z_mean = self.z_mean(x)
        z_log_var = self.z_log_var(x)
        z = self.sampling(z_mean, z_log_var)

        return z_mean, z_log_var, z

"""Creo il decoder:"""

class Decoder(nn.Module):
    def __init__(self, latent_dim=2):
        super(Decoder, self).__init__()

        self.fc = nn.Linear(latent_dim, 7 * 7 * 64)

        self.deconv1 = nn.ConvTranspose2d(64, 64, kernel_size=3, stride=2, padding=1, output_padding=1)
        self.deconv2 = nn.ConvTranspose2d(64, 32, kernel_size=3, stride=2, padding=1, output_padding=1)
        self.deconv3 = nn.ConvTranspose2d(32, 1, kernel_size=3, stride=1, padding=1)

    def forward(self, z):
        x = F.relu(self.fc(z))
        x = x.view(-1, 64, 7, 7)  # reshape

        x = F.relu(self.deconv1(x))
        x = F.relu(self.deconv2(x))
        x = torch.sigmoid(self.deconv3(x))

        return x

"""Definisco un Variation Auto Encoder (VAE):"""

class VAE(nn.Module):
    def __init__(self, encoder, decoder):
        super(VAE, self).__init__()

        self.encoder = encoder
        self.decoder = decoder

    def forward(self, x):
        z_mean, z_log_var, z = self.encoder(x)
        reconstruction = self.decoder(z)
        return reconstruction, z_mean, z_log_var


def vae_loss(x, reconstruction, z_mean, z_log_var):
    # Reconstruction loss
    reconstruction_loss = F.binary_cross_entropy(
        reconstruction,
        x,
        reduction="none"
    )

    reconstruction_loss = reconstruction_loss.sum(dim=(1, 2, 3)).mean()

    # KL divergence
    kl_loss = -0.5 * (1 + z_log_var - z_mean.pow(2) - z_log_var.exp())
    kl_loss = kl_loss.sum(dim=1).mean()

    total_loss = reconstruction_loss + kl_loss

    return total_loss, reconstruction_loss, kl_loss

"""Addestro il VAE:"""

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Load MNIST
transform = transforms.Compose([
    transforms.ToTensor(),  # converts images to [0, 1] and shape (1, 28, 28)
])

train_dataset = datasets.MNIST(
    root="./data",
    train=True,
    download=True,
    transform=transform
)

test_dataset = datasets.MNIST(
    root="./data",
    train=False,
    download=True,
    transform=transform
)


mnist_digits = torch.utils.data.ConcatDataset([train_dataset, test_dataset])

train_loader = DataLoader(
    mnist_digits,
    batch_size=128,
    shuffle=True
)

# Model
latent_dim = 2

encoder = Encoder(latent_dim=latent_dim)
decoder = Decoder(latent_dim=latent_dim)

vae = VAE(encoder, decoder).to(device)

optimizer = torch.optim.Adam(vae.parameters())

# Training loop
epochs = 30

for epoch in range(epochs):
    vae.train()

    total_loss_epoch = 0.0
    reconstruction_loss_epoch = 0.0
    kl_loss_epoch = 0.0

    for x, _ in train_loader:
        x = x.to(device)

        optimizer.zero_grad()

        reconstruction, z_mean, z_log_var = vae(x)

        total_loss, reconstruction_loss, kl_loss = vae_loss(
            x,
            reconstruction,
            z_mean,
            z_log_var
        )

        total_loss.backward()
        optimizer.step()

        total_loss_epoch += total_loss.item()
        reconstruction_loss_epoch += reconstruction_loss.item()
        kl_loss_epoch += kl_loss.item()

    num_batches = len(train_loader)

    print(
        f"Epoch [{epoch+1}/{epochs}] "
        f"loss: {total_loss_epoch / num_batches:.4f} "
        f"reconstruction_loss: {reconstruction_loss_epoch / num_batches:.4f} "
        f"kl_loss: {kl_loss_epoch / num_batches:.4f}"
    )

"""Visualizzo lo spazio latente dal VAE:"""

import matplotlib.pyplot as plt


def plot_latent_space(vae, device, n=20, figsize=15):
    vae.eval()

    digit_size = 28
    scale = 5.0
    figure = np.zeros((digit_size * n, digit_size * n))

    grid_x = np.linspace(-scale, scale, n)
    grid_y = np.linspace(-scale, scale, n)[::-1]

    with torch.no_grad():
        for i, yi in enumerate(grid_y):
            for j, xi in enumerate(grid_x):

                z_sample = torch.tensor([[xi, yi]], dtype=torch.float32).to(device)

                x_decoded = vae.decoder(z_sample)

                digit = x_decoded[0].cpu().numpy().reshape(digit_size, digit_size)

                figure[
                    i * digit_size : (i + 1) * digit_size,
                    j * digit_size : (j + 1) * digit_size,
                ] = digit

    plt.figure(figsize=(figsize, figsize))

    start_range = digit_size // 2
    end_range = n * digit_size + start_range
    pixel_range = np.arange(start_range, end_range, digit_size)

    sample_range_x = np.round(grid_x, 1)
    sample_range_y = np.round(grid_y, 1)

    plt.xticks(pixel_range, sample_range_x)
    plt.yticks(pixel_range, sample_range_y)

    plt.xlabel("z[0]")
    plt.ylabel("z[1]")
    plt.imshow(figure, cmap="Greys_r")
    plt.show()

plot_latent_space(vae, device)